### ISSUE TITLE
Issue with workspace with multiple repos

### ISSUE THREAD

**Issue by MoltenCoffee** [anish000kumar/easy-npm-support#1]
Hi, posting my issue from Reddit.
I have a workspace setup with multiple repos of an org I work for. If I use easy-npm, it only shows the package info of the first repo in the workspace.

To reproduce:
- create a new workspace in VS Code
- "Add Folder to workspace..." multiple times, each time adding a different repo
- Try to use easy-npm

<img width="289" alt="image" src="https://user-images.githubusercontent.com/13321277/230877302-b8c95b4b-264a-4467-9d30-990244f6225e.png">

**Comment by anish000kumar** [comment]
Thanks for reporting the issue. Fixed in 0.1.7.

Closing it for now. Please feel free to revive this discussion, if you have further comments.

**Comment by autoboxer** [comment]
I'm still seeing this issue in 0.1.7.  Is there a limit to how deeply you search for package.json files?  My structure is:

```
root/
  package.json
  packages/
    components/
      package.json
      component-1/
        package.json
```

**Comment by anish000kumar** [comment]
@autoboxer is there a specific depth after which you can’t see folders shown in easy-npm?

**Comment by autoboxer** [comment]
I only tested with the project structure I mentioned above, but I took another look a moment ago and all package.json files were visible in easy-npm.  I'm not sure what the refresh timer is, but that may have something to do with it.  Regardless, it's working as intended.
